name: 🚀 Deploy to Dev-Innovation

on:
  pull_request:
    types: 
      - synchronize
      - opened
      - labeled

jobs:
  build-and-deploy:
    name: 🎉 Build and Deploy
    if: contains(github.event.pull_request.labels.*.name, 'ready for review')
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 🔧 Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: 📦 Install dependencies
      run: npm install

    - name: 🛠️ Build with Eleventy
      run: |
        NODE_ENV=production npx @11ty/eleventy
      env:
        PATH_PREFIX: /simlearn/ # Set production prefix

    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.bgsandbox.com
        username: willelder@bgsandbox.com
        password: ${{ secrets.ftp_password }}
        port: 21
        local-dir: ./_site/
        server-dir: dev-innovation.bgsandbox.com/simlearn/
        exclude: |
          **/.DS_Store
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/assets/sass/**
          **/uswds/img/material-icons-deprecated/**

  lighthouse:
    name: 👀 Lighthouse Scan
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: 👀 Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://www.dev-innovation.bgsandbox.com/simlearn/index.html, https://www.dev-innovation.bgsandbox.com/simlearn/views/about/about-simlearn.html, https://www.dev-innovation.bgsandbox.com/simlearn/views/about/bio-simlearn.html, https://www.dev-innovation.bgsandbox.com/simlearn/views/about/contact.html, https://www.dev-innovation.bgsandbox.com/simlearn/views/about/history.html, https://www.dev-innovation.bgsandbox.com/simlearn/views/news-event/news-media.html, https://www.dev-innovation.bgsandbox.com/simlearn/views/portfolios/simvet.html, https://www.dev-innovation.bgsandbox.com/simlearn/views/portfolios/assessment-collaboration-aco.html, https://www.dev-innovation.bgsandbox.com/simlearn/views/portfolios/clinical-training-cte.html, https://www.dev-innovation.bgsandbox.com/simlearn/views/portfolios/learning-management.html, https://www.dev-innovation.bgsandbox.com/simlearn/views/portfolios/redi.html, https://www.dev-innovation.bgsandbox.com/simlearn/fellowship.html, https://www.dev-innovation.bgsandbox.com/simlearn/fellow-learning.html, https://www.dev-innovation.bgsandbox.com/simlearn/views/resurces-faq/faq-page.html'
        device: all  
        awsAccessKeyId: ${{ secrets.LIGHTHOUSE_CHECK_AWS_ACCESS_KEY_ID }}
        awsBucket: ${{ secrets.LIGHTHOUSE_CHECK_AWS_BUCKET }}
        awsRegion: ${{ secrets.LIGHTHOUSE_CHECK_AWS_REGION }}
        awsSecretAccessKey: ${{ secrets.LIGHTHOUSE_CHECK_AWS_SECRET_ACCESS_KEY }}
        gitAuthor: ${{ github.actor }}
        gitBranch: ${{ github.ref }}
        gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ github.sha }}
        slackWebhookUrl: ${{ secrets.LIGHTHOUSE_CHECK_WEBHOOK_URL }}
