name: "PR Merged: Zip Changed Files & Notify Slack"

on:
  pull_request:
    types: [closed]

jobs:
  notify-slack:
    # Only run if the PR was merged and its target branch is main.
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code at the merge commit
        uses: actions/checkout@v3
        with:
          # We need at least 2 commits for HEAD^ to exist
          fetch-depth: 2
          ref: ${{ github.sha }}

      - name: List changed files in the merge commit
        id: changed-files
        run: |
          # List changed files between the merge commit (HEAD) and its parent (HEAD^)
          CHANGED_FILES=$(git diff HEAD^ HEAD --name-only)
          echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_OUTPUT
          echo "Found files:" 
          echo "${CHANGED_FILES}"

      - name: Zip the changed files
        id: zip
        run: |
          # Convert the list of changed files into an array
          IFS=$'\n' read -rd '' -a files <<< "${{ steps.changed-files.outputs.CHANGED_FILES }}"
          
          # Handle the case where no files changed (or diff returns an empty string)
          if [ -z "${files[*]}" ]; then
            echo "No changed files were detected; creating an empty zip file."
            zip changed_files.zip --quiet --junk-paths --filesync /dev/null
          else
            zip changed_files.zip "${files[@]}"
          fi

      - name: Upload ZIP file to Slack
        run: |
          curl -F file=@changed_files.zip \
               -F "channels=${{ secrets.SLACK_CHANNEL_ID }}" \
               -F "initial_comment=PR #${{ github.event.pull_request.number }} merged into main. Here are the changed files:" \
               -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
               https://slack.com/api/files.upload
