name: "Upload changed files to Slack on PR merge"

on:
  pull_request:
    types: [closed]

jobs:
  upload-changes-to-slack:
    runs-on: ubuntu-latest
    # Only proceed if the PR was merged
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Check out code at the merge commit
        uses: actions/checkout@v3
        with:
          # Make sure we have enough history to use HEAD^
          fetch-depth: 2
          # Use the actual merge commit SHA
          ref: ${{ github.sha }}

      - name: Identify changed files
        id: diff
        run: |
          # Gather changed files between HEAD and HEAD^
          CHANGED_FILES=$(git diff HEAD^ HEAD --name-only)

          # If you want to see the list in the job log
          echo "Detected changed files:"
          echo "$CHANGED_FILES"

          # Convert newlines to spaces (safe for $GITHUB_OUTPUT)
          CHANGED_FILES_SINGLE_LINE=$(echo "$CHANGED_FILES" | tr '\n' ' ')

          echo "CHANGED_FILES=$CHANGED_FILES_SINGLE_LINE" >> $GITHUB_OUTPUT

      - name: Zip the changed files
        run: |
          # Pull the space-separated list from the previous step
          CHANGED_FILES="${{ steps.diff.outputs.CHANGED_FILES }}"

          # If there are no changed files, exit gracefully
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed files found. Exiting..."
            exit 0
          fi

          zip changed-files.zip $CHANGED_FILES

      - name: Upload ZIP to Slack
        run: |
          curl -F file=@changed-files.zip \
               -F "channels=${{ secrets.SLACK_CHANNEL_ID }}" \
               -F "initial_comment=PR #${{ github.event.pull_request.number }} merged. Here are the changed files." \
               -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
               https://slack.com/api/files.upload
